[project]
name = "ingest2duck"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dlt[duckdb,parquet]>=1.20.0",
    "duckdb>=1.4.3",
    "lxml>=6.0.2",
    "openpyxl>=3.1.5",
]
